# Generated by Django 5.2.1 on 2025-05-29 22:49

import django.db.models.deletion
import foodgram.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_shoppingcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('short_link', models.TextField(default=foodgram.models.random_id, primary_key=True, serialize=False)),
                ('destination', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
